### ISSUE TITLE
Setting EntityToken manually to request multiplayer server

### ISSUE THREAD

**Issue by Cherden** [PlayFab/NodeSDK#127]
Hi! I am currently working on our custom matchmaking mechanism using die NodeSDK. One part of it is to request the multiplayer server once matched using `PlayFabMultiplayer.RequestMultiplayerServer()`. For our game we are already using the MultiplayerServerSecureWebsocket software, where that functionalityis implemented. Unfortunately I cannot recreate the code in the NodeSDK, as I cannot seem to find out to set the entity token as done [here](https://github.com/chainofalliance/MultiplayerServerSecureWebsocket/blob/main/GameServer.ReverseProxy/Startup.cs#L65). Without it that, the request fails with error 1335 EntityTokenInvalid.

Is that the right approach or should I use a different way? If it is the right approach, how do I set the entity token as in the C# client?

Thanks in advance!

**Comment by simjounhax** [comment]
If you call 'GetEntityToken' in PlayFabAuthentication API, it'll set 'EntityToken' automatically, if there is 'EntityToken' property in result object.
![image](https://github.com/PlayFab/NodeSDK/assets/12342961/a9b6d98c-ba7b-4989-84a7-a46c6e1698f5)
