### ISSUE TITLE
Do not throw strings

### ISSUE THREAD

**Issue by SimonSchick** [PlayFab/NodeSDK#93]
In a lot of places you use `throw 'string'` this makes it hard to trace errors, please consider replacing these with `throw new Error('string');`

**Comment by SimonSchick** [comment]
Poke.

**Comment by pgilmorepf** [comment]
Thank you for your submission.
I agree, that we should make this change, but I don't have a timeline for when that will happen.
Sorry for the delay.

**Comment by toddbellMSFT** [comment]
Fixing this issue with https://github.com/PlayFab/SDKGenerator/pull/620
