### ISSUE TITLE
Update typings to new standards

### ISSUE THREAD

**Issue by SimonSchick** [PlayFab/NodeSDK#94]
`declare module ModuleName` is somewhat deprecated and does require additional setup, having 1 main `typings` files (see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) makes it much easier to consume this library, please consider updating accordingly.

Ideally you would have 1 `index.d.ts` files which then re-exports all the modules, the TS docs explain these things quiet well.
This also allows proper importing via the `import` keyword and makes a much better user experience.

**Comment by pgilmorepf** [comment]
Thank you for your submission.
I agree, that we should make this change, but I don't have a timeline for when that will happen.
Sorry for the delay.

**Comment by toddbellMSFT** [comment]
We are now addressing this issue here https://github.com/PlayFab/SDKGenerator/pull/621
