### ISSUE TITLE
Do not ship redundant files

### ISSUE THREAD

**Issue by SimonSchick** [PlayFab/NodeSDK#95]
This is just a minor issue.
Please consider updating your `.npmignore` to only ship files that are needed.
You can omit documentation, tests and build scripts, btw. `.npmignore` is never shipped by default.

**Comment by pgilmorepf** [comment]
Thank you for your submission.
I agree, that we should make this change, but I don't have a timeline for when that will happen.
Sorry for the delay.

**Comment by toddbellMSFT** [comment]
Fixing this issue with https://github.com/PlayFab/SDKGenerator/pull/619
