### ISSUE TITLE
Does this support async/await?

### ISSUE THREAD

**Issue by eAi** [PlayFab/NodeSDK#98]
It doesn't look like the SDK supports async/await. Is this something you intend to change?

**Comment by pgilmorepf** [comment]
API calls now return a promise object, which you can await on.
Let me know if this resolves the request.
Thanks!

**Comment by KellyBennett** [comment]
@pgilmorepf I'm confused by this statement.. The APIs do _not_ return Promises, and the functions are not defined as async 🤔 
```
 GetPlayersInSegment(
            request: PlayFabServerModels.GetPlayersInSegmentRequest | null,
            callback: PlayFabModule.ApiCallback<PlayFabServerModels.GetPlayersInSegmentResult> | null,
        ): void;
        
```
