### ISSUE TITLE
Linting error: index.d.ts on Value

### ISSUE THREAD

**Issue by RacerDelux** [PlayFab/NodeSDK#99]
Looks like a type declaration is needed on line 17. I am unsure what it should be, currently it only auto resolves to type any for me.
![image](https://user-images.githubusercontent.com/2667344/53826940-6e728800-3f3f-11e9-8684-4b3a50cfe5cf.png)

**Comment by pgilmorepf** [comment]
We have already submitted a fix, and it will be released in the next publish.
Thanks for your submission.
